extends:
  - eslint:recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  browser: true
  es6: true
  node: true
settings:
  react:
    version: "16.0"
